device: &device 'cuda'
seed: &seed 0
urdf_path: &urdf_path 'data/franka_description/robots/franka_panda.urdf'
srdf_path: &srdf_path 'data/franka_description/robots/franka_panda.srdf'

main:
  interpolate_pos_step_size: &interpolate_pos_step_size 0.05
  interpolate_rot_step_size: &interpolate_rot_step_size 0.34
  grasp_depth: 0.20
  constraint_tolerance: 0.10
  bounds_min: &bounds_min [-0.85, -0.85, 0.0]
  bounds_max: &bounds_max [0.85, 0.85, 1.2]
  sdf_voxel_size: 0.01
  vlm_camera: 0
  action_steps_per_iter: 5
  seed: *seed

env:
  video_cache_size: 2000

  bounds_min: *bounds_min
  bounds_max: *bounds_max
  interpolate_pos_step_size: *interpolate_pos_step_size
  interpolate_rot_step_size: *interpolate_rot_step_size

  robot:
    robot_config:
      name: Fetch
      type: Fetch
      obs_modalities: [rgb, depth]
      action_modalities: continuous
      action_normalize: False
      position: [-0.8, 0.0, 0.]
      grasping_mode: assisted

      controller_config:
        base:
          name: DifferentialDriveController
        arm_0:
          name: OperationalSpaceController
          kp: 250
          kp_limits: [50, 400]
          damping_ratio: 0.6
        gripper_0:
          name: MultiFingerGripperController
          command_input_limits: [0.0, 1.0]
          mode: smooth
        camera:
          name: JointController

  camera:
    data_dir: ./data/sensor

path_solver:
  opt_pos_step_size: 0.10  # controls the density of control points in the path
  opt_rot_step_size: 0.39  # controls the density of control points in the path
  opt_interpolate_pos_step_size: 0.02  # controls the density of collision checking inside optimization
  opt_interpolate_rot_step_size: 0.10
  max_collision_points: 60
  sampling_maxfun: 5000
  bounds_min: *bounds_min
  bounds_max: *bounds_max
  constraint_tolerance: 0.0001
  minimizer_options:
    maxiter: 200

subgoal_solver:
  bounds_min: *bounds_min
  bounds_max: *bounds_max
  sampling_maxfun: 5000
  max_collision_points: 60
  constraint_tolerance: 0.0001
  minimizer_options:
    maxiter: 200

keypoint_proposer:
  num_candidates_per_mask: 5
  min_dist_bt_keypoints: 0.06
  max_mask_ratio: 0.5
  device: *device
  bounds_min: *bounds_min
  bounds_max: *bounds_max
  seed: *seed

constraint_generator:
  model: gpt-4o
  temperature: 0.0
  max_tokens: 2048

visualizer:
  bounds_min: *bounds_min
  bounds_max: *bounds_max